feat: Add homepage, recruitment page, components, and customizations
Daskom-Lab/DaskomOfficial-FE pull request #1
Opened 2024-11-25 14:26 UTC by Alizaaaja4

### What does this PR do?
- Adds the `HomePage` and `RecruitmentPage` with their respective layouts and styles.
- Implements reusable components:
  - Navbar
  - Footer
  - ContentHome
  - ContentRecruitment
  - CarouselDivisi
  - CarouselEvent
- Customizes Tailwind CSS in `tailwind.config.js` to include new color schemes.
- Adds several assets (images and icons) to the `/public` folder for the website.

### Screenshots
Attached screenshots of the pages and components for reference.

### Checklist:
- [x] HomePage layout and content
- [x] RecruitmentPage layout and content
- [x] Navbar and Footer components
- [x] ContentHome and ContentRecruitment sections
- [x] CarouselDivisi and CarouselEvent
- [x] Tailwind CSS customization
- [x] New assets in `/public`

### Documentation
Screenshots of the work have been attached as a reference.
![image](https://github.com/user-attachments/assets/e76ca775-1b19-4507-ba72-dae30cf7da56)
![image](https://github.com/user-attachments/assets/2e01500f-02f5-4030-ac61-cc214cb3a0ae)
![image](https://github.com/user-attachments/assets/eb0e8af3-4009-4e3e-b215-a8dcbddf6de1)
![image](https://github.com/user-attachments/assets/7a13459d-4e5b-4855-9188-61e6774a5f39)
![image](https://github.com/user-attachments/assets/c87a9585-7434-4d32-afdb-a1cc9ced936f)
![image](https://github.com/user-attachments/assets/2f939f45-8e48-4215-9a2d-3aac51222640)

2024-11-26 05:45 UTC, DiyArc-350 commented
but overall LGTM

2024-11-26 05:50 UTC, DiyArc-350 commented on components/navbar.tsx
kinda nitpick here, i think the vertical line next to the logo need a little bit of padding

2024-11-26 05:52 UTC, DiyArc-350 commented on public/daskom icon.svg
oh, i see

2024-11-26 06:50 UTC, Alizaaaja4 commented on public/daskom icon.svg
Actually, the lines and logo have been combined into one image by the UI/UX team. However, I would ask them to revise it to be more flexible, for example separating lines as separate elements that can be managed with CSS.

2024-11-26 06:58 UTC, DiyArc-350 commented on public/daskom icon.svg
okaay

2024-11-26 08:57 UTC, Zendin110206 reviewed
I'm sorry. Is there a margin for the footer? It seems like there's a left and right margin, and I think it would be better if there were no margins (just my opinion). Overall, looks good to me

2024-11-28 09:56 UTC, Soedipo commented
> I'm sorry. Is there a margin for the footer? It seems like there's a left and right margin, and I think it would be better if there were no margins (just my opinion). Overall, looks good to me

I aggree with this, not only at footer but at the whole screen, make it zero for the margin so it has no whitespace at the sides

2024-11-28 10:06 UTC, Soedipo requested changes
Please change the margin to zero at the whole screen/body so it has no whitespace

2024-11-28 10:06 UTC, Soedipo commented on app/layout.tsx
> I'm sorry. Is there a margin for the footer? It seems like there's a left and right margin, and I think it would be better if there were no margins (just my opinion). Overall, looks good to me - @Zendin110206 

I aggree with this, not only at footer but at the whole screen, make it zero for the margin so it has no whitespace at all sides

![image](https://github.com/user-attachments/assets/79b75bb5-8764-47e6-91ab-e9b51fe3972f)

2024-12-06 02:23 UTC, Alizaaaja4 commented on app/layout.tsx
I've applied the revision to remove the margin across the entire screen. Now there’s no whitespace at all sides. Please see the updated screenshot below for confirmation:

![image](https://github.com/user-attachments/assets/3f98e050-facc-4da0-ad59-0919ab3b1895)

2024-12-06 02:56 UTC, Soedipo commented on app/layout.tsx
Okkkkk LGTM I'll approve this 😁👌

2024-12-06 02:57 UTC, Soedipo approved these changes

2024-12-06 03:03 UTC, Soedipo commented
I want to give advice for front-end team,, when PR, if there's animation or dynamic styling at your requirenment/works/PR please provide the video or maybe a GIF so we all could check it too. 
Good luck ^_^

2024-12-06 05:58 UTC, Alizaaaja4 commented
> I want to give advice for front-end team,, when PR, if there's animation or dynamic styling at your requirenment/works/PR please provide the video or maybe a GIF so we all could check it too.
> Good luck ^_^

Thank you for the suggestion! For the next PR, I will try using a GIF to showcase animations or dynamic styling to make it easier for the review 👍

2024-12-06 05:58 UTC, merged